// Generated by XenoTemplateTool v1.2 on 2018/3/23 at 22:53
using UnityEditor;
namespace CYM.Template
{
    public static class ExtendedTemplateMenuItems
    {

        [MenuItem("Assets/Templates/AutoMono", false, 0)]
        public static void AutoMono()=>TemplateTool.PromptUserForNameAuto();        
        [MenuItem("Assets/Templates/TDConfig", false, 0)]
        public static void TDConfig()=>TemplateTool.ShowTemplate("TDConfig");        
        [MenuItem("Assets/Templates/MainUIView", false, 0)]
        public static void MainUIView()=>TemplateTool.ShowTemplate("MainUIView");
        
    }

}